repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        language: system
        entry: ./scripts/hook_lint.sh
      - id: format
        name: format
        language: system
        entry: ./scripts/hook_format.sh

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
